base_url = "https://example.com"
title = "Neutral"
description = "A neutral base for very specific Zola sites"
default_language = "en"
compile_sass = true
minify_html = true
build_search_index = true

taxonomies = [
  { name = "tags" },
]

[markdown]
highlight_code = true
render_emoji = true
external_links_target_blank = true
external_links_no_follow = true
external_links_no_referrer = true
smart_punctuation = true

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

[search]
include_title = true
include_description = true
include_path = false
include_content = true

[extra.icons]
16x16 = "/16x16.png"
32x32 = "/32x32.png"

[extra.networks]
github = "gfauredev"
