# Free CDNS
# jsdelivr.com
# cdnjs.com

# TODO type: text/css by default

# Custom style
style:
  href: /style.css

########## Fonts ##########
Libre Baskerville: # Serif
  href: https://cdn.jsdelivr.net/npm/@fontsource/libre-baskerville@5
Inter: # Sans
  href: https://cdn.jsdelivr.net/npm/@fontsource/inter@5
FiraGO: # Sans
  href: https://cdn.jsdelivr.net/npm/@fontsource/firago@5
